workflows:
  android-apk:
    name: Android APK Release
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK (split by architecture)
        script: |
          flutter build apk --release \
            --split-per-abi \
            --obfuscate \
            --split-debug-info=build/debug-info
    artifacts:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
